services:
  _defaults:
    autowire: true
    public: false

  App\Web\API\:
    resource: '../../../src/Web/API/'

  App\Web\API\Action\:
    resource: '../../../src/Web/API/Action/*/*/*/*Action*'
    tags: ['controller.service_arguments']

  # Middlewares
  App\Web\API\Middleware\TokenMiddleware:
    tags: [ 'kernel.event_subscriber' ]

  App\Web\API\Middleware\ErrorHandlerMiddleware:
    tags: ['kernel.event_subscriber']

  GuzzleHttp\Client:
    class: GuzzleHttp\Client