dashboard:
  path: /
  controller: App\Web\MVC\Controller\Dashboard\DashboardController::showDashboard
  methods: GET

accounts.user.sign-in.page:
  path: /sign-in
  controller: App\Web\MVC\Controller\Accounts\Auth\AuthController::showSignInPage
  methods: GET

accounts.user.sign-in:
  path: /sign-in
  controller: App\Web\MVC\Controller\Accounts\Auth\AuthController::signIn
  methods: POST

accounts.user.register.page:
  path: /register
  controller: App\Web\MVC\Controller\Accounts\Auth\AuthController::showRegisterPage
  methods: GET

accounts.user.register:
  path: /register
  controller: App\Web\MVC\Controller\Accounts\Auth\AuthController::register
  methods: POST

accounts.user.sign-out:
  path: /sign-out
  controller: App\Web\MVC\Controller\Accounts\UserController::signOut
  methods: GET

finances.dashboard:
  path: /finances
  controller: App\Web\MVC\Controller\Finances\DashboardController::showDashboard
  methods: GET

finances.category.showAll:
  path: /finances/categories
  controller: App\Web\MVC\Controller\Finances\CategoryController::showCategoriesPage
  methods: GET

finances.category.create.page:
  path: /finances/categories/create
  controller: App\Web\MVC\Controller\Finances\CategoryController::showCreateCategoryPage
  methods: GET

finances.category.create:
  path: /finances/categories/create
  controller: App\Web\MVC\Controller\Finances\CategoryController::createCategory
  methods: POST

finances.invoice.generate:
  path: /finances/invoice/generate
  controller: App\Web\MVC\Controller\Finances\InvoiceGeneratorController::generateInvoice
  methods: POST

finances.invoice.generate.page:
  path: /finances/invoice
  controller: App\Web\MVC\Controller\Finances\InvoiceGeneratorController::showGenerateInvoicePage

multimedia.finances.invoice:
  path: /multimedia/finances/invoice
  controller: App\Web\MVC\Controller\Finances\InvoiceController::renderInvoice

webhook.invoice.was_generated_from_html:
  path: /webhook/invoice/was_generated_from_html
  controller: App\Web\MVC\Controller\WebhookController::invoiceWasGeneratedFromHtml
  methods: POST
