dashboard:
  path: /
  controller: App\Web\MVC\Action\ShowDashboardAction
  methods: GET

accounts.user.sign-in:
  path: /sign-in
  controller: App\Web\MVC\Action\Accounts\User\SignInUserAction
  methods: [GET, POST]

accounts.user.sign-out:
  path: /sign-out
  controller: App\Web\MVC\Action\Accounts\User\SignOutUserAction
  methods: GET

accounts.user.register:
  path: /register
  controller: App\Web\MVC\Action\Accounts\User\RegisterUserAction
  methods: [GET, POST]

finances.dashboard:
  path: /finances
  controller: App\Web\MVC\Action\Finances\ShowFinancesDashboardAction
  methods: GET

finances.category.showAll:
  path: /finances/categories
  controller: App\Web\MVC\Action\Finances\Category\ShowAllCategoriesAction
  methods: GET
