dashboard:
  path: /
  controller: App\Web\MVC\Action\ShowDashboardAction
  methods: GET

accounts.user.sign-in:
  path: /sign-in
  controller: App\Modules\Accounts\Infrastructure\UI\Http\Web\User\SignInUserAction
  methods: [GET, POST]

accounts.user.sign-out:
  path: /sign-out
  controller: App\Modules\Accounts\Infrastructure\UI\Http\Web\User\SignOutUserAction
  methods: GET

accounts.user.register:
  path: /register
  controller: App\Modules\Accounts\Infrastructure\UI\Http\Web\User\RegisterUserAction
  methods: [GET, POST]