services:
    _defaults:
        autowire: true
        public: false

    App\Web\MVC\:
        resource: '../../../src/Web/MVC/'

    App\Web\MVC\SPAController:
        tags: ['controller.service_arguments']
