services:
    _defaults:
        autowire: true
        public: false

    App\Web\MVC\:
        resource: '../../../src/Web/MVC/'

    App\Web\MVC\Controller\:
        resource: '../../../src/Web/MVC/Controller/'
        tags: ['controller.service_arguments']

    App\Web\MVC\Middleware\AuthTokenMiddleware:
        tags: [ 'kernel.event_subscriber' ]

    App\Web\MVC\Middleware\SecurityTokenMiddleware:
        arguments:
            $invoiceToken: '%invoice.token%'
        tags: [ 'kernel.event_subscriber' ]

    App\Web\MVC\WebHttpRequestContext:
        public: true

    GuzzleHttp\Client:
        class: GuzzleHttp\Client
