services:
  _defaults:
    autowire: true
    public: false

  App\Web\MVC\:
    resource: '../../../src/Web/MVC/'

  App\Web\MVC\Controller\:
    resource: '../../../src/Web/MVC/Controller/'
    tags: ['controller.service_arguments']

  App\Web\MVC\Middleware\TokenMiddleware:
    tags: [ 'kernel.event_subscriber' ]

  App\Web\MVC\WebHttpRequestContext:
    public: true
