services:
  _defaults:
    autowire: true
    public: false

  App\Web\MVC\Action\:
    resource: '../../../src/Web/MVC/Action/'
    tags: ['controller.service_arguments']

  App\Web\MVC\Middleware\TokenMiddleware:
    tags: [ 'kernel.event_subscriber' ]
