parameters:
  invoice.token: '%env(resolve:INVOICE_TOKEN)%'
  app.host: '%env(resolve:APP_HOST)%'
  integrations.dropbox.auth_token: '%env(resolve:DROPBOX_AUTH_TOKEN)%'

services:
  _defaults:
    autowire: true
    public: false

  App\Modules\Invoices\:
    resource: '../../../src/Modules/Invoices/'

  App\Modules\Invoices\Application\Invoice\Prepare\PrepareInvoiceHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Invoices\Application\Invoice\Prepare\PrepareInvoiceCommand

  App\Modules\Invoices\Application\Company\GetOneById\GetOneCompanyByIdHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Invoices\Application\Company\GetOneById\GetOneCompanyByIdQuery

  App\Modules\Invoices\Application\Company\GetAll\GetAllCompaniesHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Invoices\Application\Company\GetAll\GetAllCompaniesQuery

  App\Modules\Invoices\Application\Invoice\GetOneById\GetInvoiceByIdHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Invoices\Application\Invoice\GetOneById\GetInvoiceByIdQuery

  App\Modules\Invoices\Application\Filesystem\MoveFileFromApifyToDropbox\MoveFileFromApifyToDropboxHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Invoices\Application\Filesystem\MoveFileFromApifyToDropbox\MoveFileFromApifyToDropboxCommand

  App\Modules\Invoices\Application\Company\Create\CreateCompanyHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Invoices\Application\Company\Create\CreateCompanyCommand

  App\Modules\Invoices\Application\Company\Delete\DeleteCompanyHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Invoices\Application\Company\Delete\DeleteCompanyCommand

  App\Modules\Invoices\Application\Company\Update\UpdateCompanyHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Invoices\Application\Company\Update\UpdateCompanyCommand

  App\Modules\Invoices\Application\Company\UpdatePaymentInformation\UpdateCompanyPaymentInformationHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Invoices\Application\Company\UpdatePaymentInformation\UpdateCompanyPaymentInformationCommand

  App\Modules\Invoices\Domain\Invoice\PdfFromHtmlGenerator:
    class: App\Modules\Invoices\Infrastructure\Domain\Invoice\ApifyPdfFromHtmlGenerator
    arguments:
      $host: '%app.host%'
      $token: '%invoice.token%'

  App\Modules\Invoices\Domain\Filesystem\Dropbox:
    class: App\Modules\Invoices\Infrastructure\Domain\Filesystem\DropboxApiIntegration
    arguments:
      $dropboxAuthorizationToken: '%integrations.dropbox.auth_token%'