framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            async_accounts_mails:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: mails
                    queues:
                        accounts_mails: ~
            sync: 'sync://'

        routing:
            'App\Modules\Accounts\Infrastructure\Domain\Mail\SendConfirmationEmail\SendRegisterConfirmationEmailCommand': async_accounts_mails

        default_bus: command.bus
        buses:
            query.bus: ~

            command.bus:
                middleware:
                    - validation
                    - 'App\Common\Infrastructure\Messenger\Middleware\DatabaseTransactionMiddleware'
                    - 'App\Common\Infrastructure\Messenger\Middleware\DomainEventDispatcherMiddleware'

            event.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - 'App\Common\Infrastructure\Messenger\Middleware\DomainEventDispatcherMiddleware'
