twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/src/Modules/Accounts/Infrastructure/UI/Http/Web/Resource': 'Accounts'
        '%kernel.project_dir%/src/Common/Web/Resource': 'Common'
        '%kernel.project_dir%/src/Modules/Finances/Infrastructure/UI/Http/Web/Resource': 'Finances'
