version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
  h2p-microservice:
    image: feejkr/html-2-pdf
    hostname: html2pdf
    ports:
      - "8091:3000"
  db:
    image: "postgres:latest"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: default
      PGPASSWORD: default_secret
