version: '3'
services:
  app:
    build:
      context: ../
    ports:
      - "${APP_PORT}8080"
    volumes:
      - ../:/app

  invoice-generator-microservice:
    image: feejkr/invoice-generator
    ports:
      - "${HTML2PDF_MICROSERVICE_PORT}3000"
    hostname: invoice-generator-ms

  db:
    image: "postgres:latest"
    ports:
      - "${SQL_DATABASE_PORT}5432"
    environment:
      - POSTGRES_USER=${SQL_DATABASE_USER}
      - POSTGRES_PASSWORD=${SQL_DATABASE_PASSWORD}
      - PGPASSWORD=${SQL_DATABASE_ROOT_PASSWORD}

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    ports:
      - "${KEYCLOAK_PORT}8080"
    environment:
      DB_VENDOR: postgres
      DB_ADDR: keycloak-db
      DB_PORT: 5432
      DB_DATABASE: "${KEYCLOAK_DATABASE_NAME}"
      DB_USER: "${KEYCLOAK_DATABASE_USER}"
      DB_PASSWORD: "${KEYCLOAK_DATABASE_PASSWORD}"
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    depends_on:
      - keycloak-db

  keycloak-db:
    image: postgres
    container_name: keycloak-db
    ports:
      - "${KEYCLOAK_DATABASE_PORT}5432"
    environment:
      POSTGRES_DB: "${KEYCLOAK_DATABASE_NAME}"
      POSTGRES_USER: "${KEYCLOAK_DATABASE_USER}"
      POSTGRES_PASSWORD: "${KEYCLOAK_DATABASE_PASSWORD}"