accounts:
  resource: accounts.yaml

invoices:
  resource: invoices/routes.yaml
  name_prefix: api.v1.invoices.
  prefix: /api/v1/invoices

finances:
  resource: finances/routes.yaml
  name_prefix: api.v1.finances.
  prefix: /api/v1/finances