finances:
    resource: 'modules/finances/routes.yaml'

accounts:
    resource: 'modules/accounts/routes.yaml'

dashboard:
    path: /
    controller: App\Common\Web\ShowDashboardAction
    methods: GET