jwt.generate:
    path: /jwt/generate
    controller: App\UI\Web\Controller\IndexController::generateJWT

categories:
    path: /api/categories
    controller: App\UI\Web\Controller\CategoryController::index
