jwt.generate:
    path: /jwt/generate
    controller: App\UI\Web\Controller\IndexController::generateJWT

categories:
    path: /api/categories
    controller: App\UI\Web\Controller\CategoryController::fetchAll
    methods: GET

categories.oneById:
    path: /api/categories/{id}
    controller: App\UI\Web\Controller\CategoryController::fetchOneById
    methods: GET

categories.create:
    path: /api/categories
    controller: App\UI\Web\Controller\CategoryController::create
    methods: POST

categories.delete:
    path: /api/categories/{id}
    controller: App\UI\Web\Controller\CategoryController::delete
    methods: DELETE

wallets:
    path: /api/wallets
    controller: App\UI\Web\Controller\WalletController::fetchAll
    methods: GET

wallets.oneById:
    path: /api/wallets/{id}
    controller: App\UI\Web\Controller\WalletController::fetchOneById
    methods: GET