parameters:
    jwt.secret_key: '%env(resolve:JWT_SECRET_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\Common\Application\Command\CommandHandler:
            tags:
                - { name: messenger.message_handler, bus: command.bus }

        App\Common\Application\Query\QueryHandler:
            tags:
                - { name: messenger.message_handler, bus: query.bus }

    Framework\:
        resource: '../framework'

    App\Common\:
        resource: '../src/Common/'

    App\Common\Infrastructure\Request\HttpRequestContext:
        class: App\Web\API\SessionRequestContext

imports:
    - {resource: 'modules/finances/services.yaml'}
    - {resource: 'modules/accounts/services.yaml'}
    - {resource: 'modules/invoices/services.yaml'}
    - {resource: 'web/mvc/services.yaml'}
    - {resource: 'web/api/services.yaml'}
