services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $appHost: '%env(APP_HOST)%'

    Framework\:
        resource: '../framework'

    App\Common\:
        resource: '../src/Common/'

    App\Web\:
        resource: '../src/Web/'

    # Controllers
    App\Web\MVC\SPAController:
        tags: [ 'controller.service_arguments' ]

    # Middlewares
    App\Web\API\Middleware\ErrorHandlerMiddleware:
        tags: [ 'kernel.event_subscriber' ]

    GuzzleHttp\Client:
        class: GuzzleHttp\Client

