parameters:
    jwt.secret_key: '%env(resolve:JWT_SECRET_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Common\:
        resource: '../src/Common/'

    App\Common\Infrastructure\Request\HttpRequestContext:
        class: App\Web\API\ApiHttpRequestContext

imports:
    - {resource: 'modules/finances/services.yaml'}
    - {resource: 'modules/accounts/services.yaml'}
    - {resource: 'modules/invoices/services.yaml'}
    - {resource: 'web/mvc/services.yaml'}
    - {resource: 'web/api/services.yaml'}
