parameters:
    jwt.secret_key: '%env(resolve:JWT_SECRET_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Common\:
        resource: '../src/Common/'

    App\Web\HttpRequestContextFactory: ~

    App\Common\Infrastructure\Request\HttpRequestContext:
        factory: [ '@App\Web\HttpRequestContextFactory', 'build' ]

imports:
    - {resource: 'modules/finances/services.yaml'}
    - {resource: 'modules/accounts/services.yaml'}
    - {resource: 'web/mvc/services.yaml'}
    - {resource: 'web/api/services.yaml'}
