parameters:
    jwt.secret_key: '%env(resolve:JWT_SECRET_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Common\:
        resource: '../src/Common/'

imports:
    - {resource: 'modules/finances/services.yaml'}
    - {resource: 'modules/accounts/services.yaml'}
