services:
    _defaults:
        autowire: true
        autoconfigure: true

    Framework\:
        resource: '../framework'

    App\Common\:
        resource: '../src/Common/'

    App\Web\:
        resource: '../src/Web/'

    # Controllers
    App\Web\MVC\SPAController:
        tags: [ 'controller.service_arguments' ]

    App\Web\API\Action\:
        resource: '../src/Web/API/Action/*/*/*/*Action*'
        tags: [ 'controller.service_arguments' ]

    # Middlewares
    App\Web\API\Middleware\TokenMiddleware:
        tags: [ 'kernel.event_subscriber' ]

    App\Web\API\Middleware\ErrorHandlerMiddleware:
        tags: [ 'kernel.event_subscriber' ]

    GuzzleHttp\Client:
        class: GuzzleHttp\Client

