parameters:
    jwt.secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    keycloak.url: '%env(resolve:KEYCLOAK_URL)%'
    keycloak.admin.client: '%env(resolve:KEYCLOAK_ADMIN_CLIENT)%'
    keycloak.admin.secret: '%env(resolve:KEYCLOAK_ADMIN_CLIENT_SECRET)%'
    keycloak.realm: '%env(resolve:KEYCLOAK_USER_REALM)%'
    keycloak.client: '%env(resolve:KEYCLOAK_USER_CLIENT)%'
    keycloak.secret: '%env(resolve:KEYCLOAK_USER_SECRET)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Framework\:
        resource: '../framework'

    App\Common\:
        resource: '../src/Common/'

    App\Web\:
        resource: '../src/Web/'

    # Controllers
    App\Web\MVC\SPAController:
        tags: [ 'controller.service_arguments' ]

    App\Web\API\Action\:
        resource: '../src/Web/API/Action/*/*/*/*Action*'
        tags: [ 'controller.service_arguments' ]

    # Middlewares
    App\Web\API\Middleware\TokenMiddleware:
        tags: [ 'kernel.event_subscriber' ]

    App\Web\API\Middleware\ErrorHandlerMiddleware:
        tags: [ 'kernel.event_subscriber' ]

    App\Common\Infrastructure\Request\HttpRequestContext:
        class: App\Web\API\CookieRequestContext

    GuzzleHttp\Client:
        class: GuzzleHttp\Client

