services:
  _defaults:
    autowire: true
    public: false

  App\Modules\Accounts\:
    resource: '../../../src/Modules/Accounts/'

  App\Modules\Accounts\Application\User\FetchToken\FetchTokenHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Accounts\Application\User\FetchToken\FetchTokenQuery

  App\Modules\Accounts\Application\User\Register\RegisterUserHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Accounts\Application\User\Register\RegisterUserCommand

  App\Modules\Accounts\Application\User\SignIn\SignInUserHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Accounts\Application\User\SignIn\SignInUserCommand

  App\Modules\Accounts\Application\User\FetchByToken\FetchUserByTokenHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Accounts\Application\User\FetchByToken\FetchUserByTokenQuery

  App\Modules\Accounts\Application\User\SignOut\SignOutUserHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Accounts\Application\User\SignOut\SignOutUserCommand

  App\Modules\Accounts\Infrastructure\Domain\User\JWTTokenManager:
    arguments:
      $jwtSecretKey: '%jwt.secret_key%'
