categories:
  path: /api/categories
  controller: App\Modules\Finances\Infrastructure\UI\Http\Api\Category\FetchAllCategoriesAction
  methods: GET

categories.oneById:
  path: /api/categories/{id}
  controller: App\Modules\Finances\Infrastructure\UI\Http\Api\Category\FetchOneCategoryByIdAction
  methods: GET

categories.update:
  path: /api/categories/{id}
  controller: App\Modules\Finances\Infrastructure\UI\Http\Api\Category\UpdateCategoryAction
  methods: PATCH

categories.create:
  path: /api/categories
  controller: App\Modules\Finances\Infrastructure\UI\Http\Api\Category\CreateCategoryAction
  methods: POST

categories.delete:
  path: /api/categories/{id}
  controller: App\Modules\Finances\Infrastructure\UI\Http\Api\Category\DeleteCategoryAction
  methods: DELETE

wallets:
  path: /api/wallets
  controller: App\Modules\Finances\Infrastructure\UI\Http\Api\Wallet\FetchAllWalletsAction
  methods: GET

wallets.oneById:
  path: /api/wallets/{id}
  controller: App\Modules\Finances\Infrastructure\UI\Http\Api\Wallet\FetchOneWalletByIdAction
  methods: GET

wallets.create:
  path: /api/wallets
  controller: App\Modules\Finances\Infrastructure\UI\Http\Api\Wallet\CreateWalletAction
  methods: POST

wallets.update:
  path: /api/wallets/{id}
  controller: App\Modules\Finances\Infrastructure\UI\Http\Api\Wallet\UpdateWalletAction
  methods: PATCH

wallets.delete:
  path: /api/wallets/{id}
  controller: App\Modules\Finances\Infrastructure\UI\Http\Api\Wallet\DeleteWalletAction
  methods: DELETE

wallet.transactions:
  path: /api/wallets/{wallet_id}/transactions
  controller: App\Modules\Finances\Infrastructure\UI\Http\Api\Transaction\FetchAllTransactionsByWalletIdAction
  methods: GET

transactions.oneById:
  path: /api/transactions/{id}
  controller: App\Modules\Finances\Infrastructure\UI\Http\Api\Transaction\FetchOneTransactionByIdAction
  methods: GET

transactions:
  path: /api/transactions
  controller: App\Modules\Finances\Infrastructure\UI\Http\Api\Transaction\FetchAllTransactionsAction
  methods: GET

transactions.create:
  path: /api/transactions
  controller: App\Modules\Finances\Infrastructure\UI\Http\Api\Transaction\CreateTransactionAction
  methods: POST

transactions.update:
  path: /api/transactions/{id}
  controller: App\Modules\Finances\Infrastructure\UI\Http\Api\Transaction\UpdateTransactionAction
  methods: PATCH

transactions.delete:
  path: /api/transactions/{id}
  controller: App\Modules\Finances\Infrastructure\UI\Http\Api\Transaction\DeleteTransactionAction
  methods: DELETE