parameters:
  jwt.secret_key: '%env(resolve:JWT_SECRET_KEY)%'

services:
  _defaults:
    autowire: true
    public: false

  App\Modules\Finances\:
    resource: '../../../src/Modules/Finances/'

  App\Modules\Finances\Infrastructure\UI\Http\Api\:
    resource: '../../../src/Modules/Finances/Infrastructure/UI/Http/Api/'
    tags: ['controller.service_arguments']

  App\Modules\Finances\Application\Category\Create\CreateCategoryHandler:
    tags:
      -
        name: messenger.message_handler
        handles: App\Modules\Finances\Application\Category\Create\CreateCategoryCommand

  App\Modules\Finances\Application\Category\Delete\DeleteCategoryHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Category\Delete\DeleteCategoryCommand

  App\Modules\Finances\Application\Category\Update\UpdateCategoryHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Category\Update\UpdateCategoryCommand

  App\Modules\Finances\Application\Category\FetchAll\FetchAllCategoriesHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Category\FetchAll\FetchAllCategoriesQuery

  App\Modules\Finances\Application\Category\FetchOneById\FetchOneCategoryByIdHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Category\FetchOneById\FetchOneCategoryByIdQuery

  App\Modules\Finances\Application\Wallet\Create\CreateWalletHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Wallet\Create\CreateWalletCommand

  App\Modules\Finances\Application\Wallet\Delete\DeleteWalletHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Wallet\Delete\DeleteWalletCommand

  App\Modules\Finances\Application\Wallet\FetchAll\FetchAllWalletsHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Wallet\FetchAll\FetchAllWalletsQuery

  App\Modules\Finances\Application\Wallet\FetchOneById\FetchOneWalletByIdHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Wallet\FetchOneById\FetchOneWalletByIdQuery

  App\Modules\Finances\Application\Wallet\Update\UpdateWalletHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Wallet\Update\UpdateWalletCommand