parameters:
  jwt.secret_key: '%env(resolve:JWT_SECRET_KEY)%'

services:
  _defaults:
    autowire: true
    public: false

  App\:
    resource: '../../../src/*'
    exclude: '../../../src/{DependencyInjection,Entity,Tests,Kernel.php}'

  App\UI\Web\Action\:
    resource: '../../../src/UI/Web/Action/'
    tags: ['controller.service_arguments']

  App\Modules\Finances\Infrastructure\UI\Http\Api\:
    resource: '../../../src/Modules/Finances/Infrastructure/UI/Http/Api/'
    tags: ['controller.service_arguments']

  App\SharedKernel\Events\TokenSubscriber:
    arguments:
      $jwtSecretKey: '%jwt.secret_key%'
    tags: ['kernel.event_subscriber']

  App\UI\Web\Action\GenerateJWTTokenAction:
    arguments:
      $jwtSecretKey: '%jwt.secret_key%'
    tags: ['controller.service_arguments']

  category.database_repository:
    class: App\Modules\Finances\Infrastructure\Domain\Category\Doctrine\CategoryReadModelRepository
  category.cache_repository:
    class: App\Modules\Finances\Infrastructure\Domain\Category\Redis\CategoryReadModelRepository
    arguments:
      App\Modules\Finances\Application\Category\CategoryReadModelRepository: '@category.database_repository'
  category.domain_repository:
    class: App\Modules\Finances\Infrastructure\Domain\Category\Doctrine\CategoryRepository

  App\Modules\Finances\Application\Category\CategoryService:
    arguments:
      App\Modules\Finances\Domain\Category\CategoryRepository: '@category.domain_repository'

  App\Modules\Finances\Application\Category\CategoryReadModel:
    arguments:
      $repository: '@category.cache_repository'

  wallet.database_repository:
    class: App\Modules\Finances\Infrastructure\Domain\Wallet\Doctrine\WalletReadModelRepository
  wallet.cache_repository:
    class: App\Modules\Finances\Infrastructure\Domain\Wallet\Redis\WalletReadModelRepository
    arguments:
      App\Modules\Finances\Application\Wallet\WalletReadModelRepository: '@wallet.database_repository'

  App\Modules\Finances\Application\Wallet\WalletReadModel:
    class: App\Modules\Finances\Application\Wallet\WalletReadModel
    arguments:
      App\Modules\Finances\Application\Wallet\WalletReadModelRepository: '@wallet.cache_repository'

  transaction.database_repository:
    class: App\Modules\Finances\Infrastructure\Domain\Transaction\Doctrine\TransactionReadModelRepository
  transaction.cache_repository:
    class: App\Modules\Finances\Infrastructure\Domain\Transaction\Redis\TransactionReadModelRepository
    arguments:
      App\Modules\Finances\Application\Transaction\TransactionReadModelRepository: '@transaction.database_repository'

  App\Modules\Finances\Application\Transaction\TransactionReadModel:
    arguments:
      $repository: '@transaction.cache_repository'