parameters:
  jwt.secret_key: '%env(resolve:JWT_SECRET_KEY)%'

services:
  _defaults:
    autowire: true
    public: false

  App\Modules\Finances\:
    resource: '../../../src/Modules/Finances/'

  App\Modules\Finances\Application\Category\Create\CreateCategoryHandler:
    tags:
      -
        name: messenger.message_handler
        handles: App\Modules\Finances\Application\Category\Create\CreateCategoryCommand

  App\Modules\Finances\Application\Category\Delete\DeleteCategoryHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Category\Delete\DeleteCategoryCommand

  App\Modules\Finances\Application\Category\Update\UpdateCategoryHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Category\Update\UpdateCategoryCommand

  App\Modules\Finances\Application\Category\FetchAll\FetchAllCategoriesHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Category\FetchAll\FetchAllCategoriesQuery

  App\Modules\Finances\Application\Category\FetchOneById\FetchOneCategoryByIdHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Category\FetchOneById\FetchOneCategoryByIdQuery

  App\Modules\Finances\Application\Wallet\Create\CreateWalletHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Wallet\Create\CreateWalletCommand

  App\Modules\Finances\Application\Wallet\Delete\DeleteWalletHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Wallet\Delete\DeleteWalletCommand

  App\Modules\Finances\Application\Wallet\FetchAll\FetchAllWalletsHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Wallet\FetchAll\FetchAllWalletsQuery

  App\Modules\Finances\Application\Wallet\FetchOneById\FetchOneWalletByIdHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Wallet\FetchOneById\FetchOneWalletByIdQuery

  App\Modules\Finances\Application\Wallet\Update\UpdateWalletHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Wallet\Update\UpdateWalletCommand

  App\Modules\Finances\Application\Transaction\Create\CreateTransactionHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Transaction\Create\CreateTransactionCommand

  App\Modules\Finances\Application\Transaction\Delete\DeleteTransactionHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Transaction\Delete\DeleteTransactionCommand

  App\Modules\Finances\Application\Transaction\Update\UpdateTransactionHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Transaction\Update\UpdateTransactionCommand

  App\Modules\Finances\Application\Transaction\FetchAll\FetchAllTransactionsHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Transaction\FetchAll\FetchAllTransactionsQuery

  App\Modules\Finances\Application\Transaction\FetchAllByWallet\FetchAllTransactionsByWalletHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Transaction\FetchAllByWallet\FetchAllTransactionsByWalletQuery

  App\Modules\Finances\Application\Transaction\FetchOneById\FetchOneTransactionByIdHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Transaction\FetchOneById\FetchOneTransactionByIdQuery
