services:
  _defaults:
    autowire: true
    public: false

  App\Modules\Finances\:
    resource: '../../../src/Modules/Finances/'

  App\Modules\Finances\Application\Category\Create\CreateCategoryHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Category\Create\CreateCategoryCommand

  App\Modules\Finances\Application\Category\Delete\DeleteCategoryHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Category\Delete\DeleteCategoryCommand

  App\Modules\Finances\Application\Category\Update\UpdateCategoryHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Category\Update\UpdateCategoryCommand

  App\Modules\Finances\Application\Category\GetAll\GetAllCategoriesHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Category\GetAll\GetAllCategoriesQuery

  App\Modules\Finances\Application\Category\GetOneById\GetOneCategoryByIdHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Category\GetOneById\GetOneCategoryByIdQuery

  App\Modules\Finances\Application\Category\GetAllGroupedByType\GetAllGroupedByTypeHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Category\GetAllGroupedByType\GetAllGroupedByTypeQuery

  App\Modules\Finances\Application\Wallet\Create\CreateWalletHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Wallet\Create\CreateWalletCommand

  App\Modules\Finances\Application\Wallet\Delete\DeleteWalletHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Wallet\Delete\DeleteWalletCommand

  App\Modules\Finances\Application\Wallet\GetAll\GetAllWalletsHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Wallet\GetAll\GetAllWalletsQuery

  App\Modules\Finances\Application\Wallet\GetOneById\GetOneWalletByIdHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Wallet\GetOneById\GetOneWalletByIdQuery

  App\Modules\Finances\Application\Wallet\Update\UpdateWalletHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Wallet\Update\UpdateWalletCommand

  App\Modules\Finances\Application\Transaction\Create\CreateTransactionHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Transaction\Create\CreateTransactionCommand

  App\Modules\Finances\Application\Transaction\Delete\DeleteTransactionHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Transaction\Delete\DeleteTransactionCommand

  App\Modules\Finances\Application\Transaction\Update\UpdateTransactionHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Transaction\Update\UpdateTransactionCommand

  App\Modules\Finances\Application\Transaction\GetAll\GetAllTransactionsHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Transaction\GetAll\GetAllTransactionsQuery

  App\Modules\Finances\Application\Transaction\GetAllByWallet\GetAllTransactionsByWalletHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Transaction\GetAllByWallet\GetAllTransactionsByWalletQuery

  App\Modules\Finances\Application\Transaction\GetOneById\GetOneTransactionByIdHandler:
    tags:
      - name: messenger.message_handler
        handles: App\Modules\Finances\Application\Transaction\GetOneById\GetOneTransactionByIdQuery
