parameters:
  jwt.secret_key: '%env(resolve:JWT_SECRET_KEY)%'

services:
  _defaults:
    autowire: true
    public: false

  App\Modules\Finances\:
    resource: '../../../src/Modules/Finances/'

  App\Modules\Finances\Infrastructure\UI\Http\Api\:
    resource: '../../../src/Modules/Finances/Infrastructure/UI/Http/Api/'
    tags: ['controller.service_arguments']
